# Generated by Django 3.2.6 on 2021-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('postalCode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
