# Generated by Django 3.2.6 on 2021-11-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
